version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: spoofing_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: spoofing_db
      MYSQL_USER: spoofing_user
      MYSQL_PASSWORD: spoofing_password
    ports:
      - "4306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: spoofing_redis
    ports:
      - "6379:6379"
    restart: unless-stopped

volumes:
  mysql_data: