# MySQL Database Configuration
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/spoofing_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:spoofing_user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:password}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA Configuration
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

# Redis Configuration
spring.data.redis.host=${SPRING_REDIS_HOST:localhost}
spring.data.redis.port=${SPRING_REDIS_PORT:6379}
spring.cache.type=redis

# Disable Docker Compose in production
spring.docker.compose.enabled=false

# Server Configuration
server.port=8081

# JWT Configuration
jwt.secret=myVerySecretKeyForJWTTokenGenerationThatShouldBeLongEnough
jwt.expiration=86400000