spring:
  datasource:
    url: jdbc:mysql://localhost:4306/spoofing_db
    username: spoofing_user
    password: spoofing_password
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  
  data:
    redis:
      host: localhost
      port: 6379
  
  cache:
    type: redis
  
  docker:
    compose:
      enabled: true

server:
  port: 8081

jwt:
  secret: myVerySecretKeyForJWTTokenGenerationThatShouldBeLongEnough
  expiration: 86400000