spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:4306/spoofing_db}
    username: ${SPRING_DATASOURCE_USERNAME:spoofing_user}
    password: ${SPRING_DATASOURCE_PASSWORD:spoofing_password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false
  
  data:
    redis:
      host: ${SPRING_REDIS_HOST:localhost}
      port: ${SPRING_REDIS_PORT:6379}
  
  cache:
    type: redis
  
  docker:
    compose:
      enabled: false

server:
  port: 8081

jwt:
  secret: myVerySecretKeyForJWTTokenGenerationThatShouldBeLongEnough
  expiration: 86400000

logging:
  level:
    com.itasca.spoofing: INFO
    org.springframework.security: WARN