name: Deploy to Production

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: self-hosted
    
    steps:
    - name: Checkout and deploy
      run: |
        cd /opt/spoofing || mkdir -p /opt/spoofing && cd /opt/spoofing
        if [ -d ".git" ]; then
          git pull origin main
        else
          git clone ${{ github.server_url }}/${{ github.repository }}.git .
        fi
        cat > .env << EOF
        MYSQL_ROOT_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }}
        MYSQL_DATABASE=${{ secrets.MYSQL_DATABASE }}
        MYSQL_USER=${{ secrets.MYSQL_USER }}
        MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }}
        EOF
        docker-compose -f docker-compose.prod.yml down
        docker-compose -f docker-compose.prod.yml up -d --build